CREATE TABLE ITSOBANK.ACCOUNT (id VARCHAR(255) NOT NULL, balance NUMERIC, PRIMARY KEY (id)) ENGINE = innodb;
CREATE TABLE ITSOBANK.ACCOUNT_CUSTOMER (ACCOUNT_ID VARCHAR(255), CUSTOMER_SSN VARCHAR(255)) ENGINE = innodb;
CREATE TABLE ITSOBANK.CUSTOMER (ssn VARCHAR(255) NOT NULL, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), title VARCHAR(255), PRIMARY KEY (ssn)) ENGINE = innodb;
CREATE TABLE ITSOBANK.TRANSACT (id VARCHAR(255) NOT NULL, amount NUMERIC, TRANS_TIME DATETIME, TRANS_TYPE VARCHAR(32), ACCOUNT_ID VARCHAR(255), PRIMARY KEY (id)) ENGINE = innodb;
CREATE INDEX I_TRNSACT_DTYPE ON ITSOBANK.TRANSACT (TRANS_TYPE);
ALTER TABLE ITSOBANK.ACCOUNT_CUSTOMER ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ITSOBANK.ACCOUNT (id);
ALTER TABLE ITSOBANK.ACCOUNT_CUSTOMER ADD FOREIGN KEY (CUSTOMER_SSN) REFERENCES ITSOBANK.CUSTOMER (ssn);
ALTER TABLE ITSOBANK.TRANSACT ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ITSOBANK.ACCOUNT (id);
