//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.rad8.mtom;

import java.awt.Image;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ProcessDocumentDelegate", targetNamespace = "http://mtom.rad8.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessDocumentDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendWordFile", targetNamespace = "http://mtom.rad8.ibm.com/", className = "com.ibm.rad8.mtom.SendWordFile")
    @ResponseWrapper(localName = "sendWordFileResponse", targetNamespace = "http://mtom.rad8.ibm.com/", className = "com.ibm.rad8.mtom.SendWordFileResponse")
    public byte[] sendWordFile(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.awt.Image
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendImage", targetNamespace = "http://mtom.rad8.ibm.com/", className = "com.ibm.rad8.mtom.SendImage")
    @ResponseWrapper(localName = "sendImageResponse", targetNamespace = "http://mtom.rad8.ibm.com/", className = "com.ibm.rad8.mtom.SendImageResponse")
    public Image sendImage(
        @WebParam(name = "arg0", targetNamespace = "")
        Image arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendPDFFile", targetNamespace = "http://mtom.rad8.ibm.com/", className = "com.ibm.rad8.mtom.SendPDFFile")
    @ResponseWrapper(localName = "sendPDFFileResponse", targetNamespace = "http://mtom.rad8.ibm.com/", className = "com.ibm.rad8.mtom.SendPDFFileResponse")
    public DataHandler sendPDFFile(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0);

}
