//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.rad8.mtom;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.rad8.mtom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendWordFile_QNAME = new QName("http://mtom.rad8.ibm.com/", "sendWordFile");
    private final static QName _SendWordFileResponse_QNAME = new QName("http://mtom.rad8.ibm.com/", "sendWordFileResponse");
    private final static QName _SendImageResponse_QNAME = new QName("http://mtom.rad8.ibm.com/", "sendImageResponse");
    private final static QName _SendPDFFile_QNAME = new QName("http://mtom.rad8.ibm.com/", "sendPDFFile");
    private final static QName _SendPDFFileResponse_QNAME = new QName("http://mtom.rad8.ibm.com/", "sendPDFFileResponse");
    private final static QName _SendImage_QNAME = new QName("http://mtom.rad8.ibm.com/", "sendImage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.rad8.mtom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendImage }
     * 
     */
    public SendImage createSendImage() {
        return new SendImage();
    }

    /**
     * Create an instance of {@link SendImageResponse }
     * 
     */
    public SendImageResponse createSendImageResponse() {
        return new SendImageResponse();
    }

    /**
     * Create an instance of {@link SendPDFFile }
     * 
     */
    public SendPDFFile createSendPDFFile() {
        return new SendPDFFile();
    }

    /**
     * Create an instance of {@link SendPDFFileResponse }
     * 
     */
    public SendPDFFileResponse createSendPDFFileResponse() {
        return new SendPDFFileResponse();
    }

    /**
     * Create an instance of {@link SendWordFile }
     * 
     */
    public SendWordFile createSendWordFile() {
        return new SendWordFile();
    }

    /**
     * Create an instance of {@link SendWordFileResponse }
     * 
     */
    public SendWordFileResponse createSendWordFileResponse() {
        return new SendWordFileResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendWordFile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mtom.rad8.ibm.com/", name = "sendWordFile")
    public JAXBElement<SendWordFile> createSendWordFile(SendWordFile value) {
        return new JAXBElement<SendWordFile>(_SendWordFile_QNAME, SendWordFile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendWordFileResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mtom.rad8.ibm.com/", name = "sendWordFileResponse")
    public JAXBElement<SendWordFileResponse> createSendWordFileResponse(SendWordFileResponse value) {
        return new JAXBElement<SendWordFileResponse>(_SendWordFileResponse_QNAME, SendWordFileResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendImageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mtom.rad8.ibm.com/", name = "sendImageResponse")
    public JAXBElement<SendImageResponse> createSendImageResponse(SendImageResponse value) {
        return new JAXBElement<SendImageResponse>(_SendImageResponse_QNAME, SendImageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendPDFFile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mtom.rad8.ibm.com/", name = "sendPDFFile")
    public JAXBElement<SendPDFFile> createSendPDFFile(SendPDFFile value) {
        return new JAXBElement<SendPDFFile>(_SendPDFFile_QNAME, SendPDFFile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendPDFFileResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mtom.rad8.ibm.com/", name = "sendPDFFileResponse")
    public JAXBElement<SendPDFFileResponse> createSendPDFFileResponse(SendPDFFileResponse value) {
        return new JAXBElement<SendPDFFileResponse>(_SendPDFFileResponse_QNAME, SendPDFFileResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendImage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mtom.rad8.ibm.com/", name = "sendImage")
    public JAXBElement<SendImage> createSendImage(SendImage value) {
        return new JAXBElement<SendImage>(_SendImage_QNAME, SendImage.class, null, value);
    }

}
