//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.rad8.mtom;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ProcessDocumentService", targetNamespace = "http://mtom.rad8.ibm.com/", wsdlLocation = "WEB-INF/wsdl/ProcessDocumentService.wsdl")
public class ProcessDocumentService
    extends Service
{

    private final static URL PROCESSDOCUMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSDOCUMENTSERVICE_EXCEPTION;
    private final static QName PROCESSDOCUMENTSERVICE_QNAME = new QName("http://mtom.rad8.ibm.com/", "ProcessDocumentService");

    static {
            PROCESSDOCUMENTSERVICE_WSDL_LOCATION = com.ibm.rad8.mtom.ProcessDocumentService.class.getResource("/WEB-INF/wsdl/ProcessDocumentService.wsdl");
        WebServiceException e = null;
        if (PROCESSDOCUMENTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/ProcessDocumentService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROCESSDOCUMENTSERVICE_EXCEPTION = e;
    }

    public ProcessDocumentService() {
        super(__getWsdlLocation(), PROCESSDOCUMENTSERVICE_QNAME);
    }

    public ProcessDocumentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSDOCUMENTSERVICE_QNAME, features);
    }

    public ProcessDocumentService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSDOCUMENTSERVICE_QNAME);
    }

    public ProcessDocumentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSDOCUMENTSERVICE_QNAME, features);
    }

    public ProcessDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessDocumentDelegate
     */
    @WebEndpoint(name = "ProcessDocumentPort")
    public ProcessDocumentDelegate getProcessDocumentPort() {
        return super.getPort(new QName("http://mtom.rad8.ibm.com/", "ProcessDocumentPort"), ProcessDocumentDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessDocumentDelegate
     */
    @WebEndpoint(name = "ProcessDocumentPort")
    public ProcessDocumentDelegate getProcessDocumentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mtom.rad8.ibm.com/", "ProcessDocumentPort"), ProcessDocumentDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSDOCUMENTSERVICE_EXCEPTION!= null) {
            throw PROCESSDOCUMENTSERVICE_EXCEPTION;
        }
        return PROCESSDOCUMENTSERVICE_WSDL_LOCATION;
    }

}
