//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package itso.rad8.bank.model.simple;

import javax.xml.ws.WebFault;

@WebFault(name = "AccountDoesNotExistException", targetNamespace = "http://simple.model.bank.rad8.itso/")
public class AccountDoesNotExistException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccountDoesNotExistException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AccountDoesNotExistException_Exception(String message, AccountDoesNotExistException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public AccountDoesNotExistException_Exception(String message, AccountDoesNotExistException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: itso.rad8.bank.model.simple.AccountDoesNotExistException
     */
    public AccountDoesNotExistException getFaultInfo() {
        return faultInfo;
    }

}
