//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://simple.model.bank.rad8.itso/")
package itso.rad8.bank.model.simple;
